spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://10.40.27.36:3306/halodoc1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      url: jdbc:mysql://localhost:3306/halodoc1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      #      password: 545411

